version: '3.7'
services:
  flask_app:
    # Собираем контейнер с приложением с помощью uwsgi.Dockerfile
    # Присваеваем имя контейнера "flask_app"
    build:
      context: ./app
      dockerfile: uwsgi.Dockerfile

    container_name: flask_app


  nginx_server:
    # Собираем контейнер с приложением с помощью /nginx/Dockerfile
    # Открываем 8000 порт для внешнего мира
    # Присваеваем имя контейнера "nginx_server"

    build:
      context: ./nginx
    ports:
      - 8000:8000
    container_name: nginx_server
